platform :ios, '8.0'
use_frameworks!
#pod 'AFNetworking', '~> 3.1.0'
pod 'ReactiveCocoa', '~> 4.0.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'WebViewJavascriptBridge', '~> 5.0.5'
pod 'QuickDialog', '~> 1.1.0'
pod 'LLBootstrapButton', '~> 0.0.1'
pod 'iCarousel', '~> 1.8.2'
pod 'NHArrowView', '~> 0.1.0'
pod 'MJRefresh', '~> 3.1.0'
pod 'TITokenField', '~> 0.9.5'
pod 'SMVerticalSegmentedControl', '~> 0.1.2'
pod 'PPiFlatSegmentedControl', '~> 1.4.0'
pod 'ZZPopoverWindow', '~> 1.0.0'
pod 'MLPAutoCompleteTextField', '~> 1.5'
pod 'BEMCheckBox', '~> 1.2.1'
pod 'UIView+FrameEx', '~> 0.0.1'
pod 'DSCarouselView', '~> 1.1.9'
pod 'M80AttributedLabel', '~> 1.3.3'
#pod 'TTAnimations', '~> 1.3'
#pod 'TTModalView', '~> 1.0.1'
pod 'TPKeyboardAvoiding', '~> 1.3'
#pod 'PromiseKit', '~> 3.1.1'
pod 'PromiseKit-AFNetworking', '~> 0.6.0'
#pod 'KeychainItemWrapper', '~> 1.2'
